name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: release

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4.1.2

    - name: Install Node.js
      uses: actions/setup-node@v4.0.2
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Build React App
      run: npm run build

    - name: Configure SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy via SSH
      run: |
        scp -r ./dist/* ubuntu@areyouhere.today:~/project/areyouhere-web

    - name: Restart Nginx
      run: |
        ssh ubuntu@areyouhere.today 'sudo systemctl restart nginx'
